######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 8 14:59:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
